version: 0.2

batch:
  fast-fail: false
  build-graph:
    - identifier: arm64
      ignore-failure: true
      env:
        compute-type: BUILD_GENERAL1_SMALL
        type: ARM_CONTAINER
        image: aws/codebuild/amazonlinux2-aarch64-standard:2.0
    - identifier: amd64
      env:
        compute-type: BUILD_GENERAL1_SMALL
        type: LINUX_CONTAINER
    - identifier: manifest
      ignore-failure: true
      buildspec: docker_manifest_buildspec.yml
      depend-on:
        - arm64
        - amd64

phases:
  install:
    commands:
      - echo "We're here"
  pre_build:
    commands:
      - echo "prebuild"
  build:
    commands:
      - echo "Build started on `date`"
  post_build:
    commands:
      - echo "Build completed on `date`"
